15:48:26.371 [main] INFO  f.i.s.repairnator.pipeline.Launcher - PIPELINE VERSION: 3.0-2018-08-09 19:04
15:48:26.482 [main] INFO  f.i.s.repairnator.pipeline.Launcher - The pipeline will try to reproduce a bug from build 324083137 and its corresponding patch from build 324196490
15:48:26.483 [main] INFO  f.i.s.repairnator.pipeline.Launcher - Initialize file serializer engines.
15:48:26.484 [main] INFO  f.i.s.repairnator.pipeline.Launcher - MongoDB won't be used for serialization.
15:48:26.485 [main] INFO  f.i.s.repairnator.pipeline.Launcher - The email notifier engine won't be used.
15:48:26.488 [main] INFO  f.i.s.repairnator.pipeline.Launcher - Start by getting the build (buildId: 324083137) with the following config: RepairnatorConfig{runId='1c2dcf8c-1783-41b0-9cdb-5cb8478a1ab9_01-18-week1-PASSING_AND_PASSING', launcherMode=BEARS, serializeJson=true, inputPath='null', outputPath='/var/log', mongodbHost='null', mongodbName='repairnator', smtpServer='null', notifyTo=[], notifyEndProcess=false, push=true, pushRemoteRepo='https://github.com/fermadeiral/bears-collection-pp', fork=false, lookFromDate=null, lookToDate=null, buildId=324083137, z3solverPath='./z3_for_linux', workspacePath='./workspace', githubToken='c8a341a903[...]', dockerImageName='null', skipDelete=false, createOutputDir=false, logDirectory='null', nbThreads=0, globalTimeout=0, whiteList=null, blackList=null, jobSleepTime=0, buildSleepTime=0, maxInspectedBuilds=0, duration=null, humanPatch=false, repository='null', clean=true, bearsMode=BOTH, bearsDelimiter = false, repairTools=NopolAllTests,NPEFix,AssertFixer,AstorJGenProg,AstorJKali,NopolSingleTest,AstorJMut,NopolTestExclusionStrategy, githubUserName= fermadeiral, githubUserEmail=fer.madeiral@gmail.com}
15:48:47.051 [main] DEBUG fr.inria.jtravis.helpers.BuildHelper - Error while executing the request (api.travis-ci.org: Name or service not known). Let's try it again.
15:48:47.052 [main] DEBUG fr.inria.jtravis.helpers.BuildHelper - Error while executing the request (api.travis-ci.org). Let's try it again.
15:48:47.056 [main] ERROR fr.inria.jtravis.helpers.BuildHelper - Error while getting JSON at URL: https://api.travis-ci.org/build/324083137
java.net.UnknownHostException: api.travis-ci.org
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at okhttp3.Dns$1.lookup(Dns.java:40)
	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at fr.inria.jtravis.helpers.AbstractHelper.get(AbstractHelper.java:102)
	at fr.inria.jtravis.helpers.AbstractHelper.get(AbstractHelper.java:122)
	at fr.inria.jtravis.helpers.AbstractHelper.get(AbstractHelper.java:122)
	at fr.inria.jtravis.helpers.AbstractHelper.get(AbstractHelper.java:94)
	at fr.inria.jtravis.helpers.EntityHelper.getEntityFromUri(EntityHelper.java:35)
	at fr.inria.jtravis.helpers.BuildHelper.fromId(BuildHelper.java:63)
	at fr.inria.spirals.repairnator.pipeline.Launcher.getBuildToBeInspected(Launcher.java:299)
	at fr.inria.spirals.repairnator.pipeline.Launcher.mainProcess(Launcher.java:350)
	at fr.inria.spirals.repairnator.pipeline.Launcher.main(Launcher.java:386)
15:48:47.057 [main] ERROR f.i.s.repairnator.pipeline.Launcher - Error while retrieving the buggy build. The process will exit now.
